/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/me/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                /** User */
                profile: {
                  id: string
                  email: string
                  roles: ('seller' | 'customer' | 'admin')[]
                }
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/refresh-token': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie: {
          refreshToken: string
        }
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** IRefreshTokenResponse */
              data: {
                accessToken: string
              }
            }
          }
        }
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: null
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            code: string
            /** Format: email */
            email: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** ILoginConfirmResponse */
              data: {
                accessToken: string
                /** User */
                profile: {
                  id: string
                  email: string
                  roles: ('seller' | 'customer' | 'admin')[]
                }
              }
            }
          }
        }
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/good-categories/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** GoodCategory */
              data: {
                id: number
                title: string
                description: string
                image: string
                /** @default null */
                parentId: null | number
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** GoodCategory */
              data: {
                id: number
                title: string
                description: string
                image: string
                /** @default null */
                parentId: null | number
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: number
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            title?: string
            description?: string
            image?: string
            /** @default null */
            parentId?: null | number
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** GoodCategory */
              data: {
                id: number
                title: string
                description: string
                image: string
                /** @default null */
                parentId: null | number
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
  '/api/good-categories/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: number
                title: string
                description: string
                image: string
                /** @default null */
                parentId: null | number
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            title: string
            description: string
            image: string
            /** @default null */
            parentId?: null | number
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** GoodCategory */
              data: {
                id: number
                title: string
                description: string
                image: string
                /** @default null */
                parentId: null | number
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/good/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Good */
              data: {
                id: string
                status: 'draft' | 'published'
                title: string
                /** @default  */
                description: string
                price: number
                /** @default null */
                priceWithDisc: null | number
                /** @default 0 */
                count: number
                /** @default [] */
                images: string[]
                /** @default null */
                categoryId: null | number
                /** @default null */
                brandId: null | string
                modifiedName?: string
                articleNumber?: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Good */
              data: {
                id: string
                status: 'draft' | 'published'
                title: string
                /** @default  */
                description: string
                price: number
                /** @default null */
                priceWithDisc: null | number
                /** @default 0 */
                count: number
                /** @default [] */
                images: string[]
                /** @default null */
                categoryId: null | number
                /** @default null */
                brandId: null | string
                modifiedName?: string
                articleNumber?: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            status?: 'draft' | 'published'
            title?: string
            /** @default  */
            description?: string
            price?: number
            /** @default null */
            priceWithDisc?: null | number
            /** @default 0 */
            count?: number
            /** @default [] */
            images?: string[]
            /** @default null */
            categoryId?: null | number
            /** @default null */
            brandId?: null | string
            modifiedName?: string
            articleNumber?: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Good */
              data: {
                id: string
                status: 'draft' | 'published'
                title: string
                /** @default  */
                description: string
                price: number
                /** @default null */
                priceWithDisc: null | number
                /** @default 0 */
                count: number
                /** @default [] */
                images: string[]
                /** @default null */
                categoryId: null | number
                /** @default null */
                brandId: null | string
                modifiedName?: string
                articleNumber?: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
  '/api/good/{id}/group': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                status: 'draft' | 'published'
                title: string
                /** @default  */
                description: string
                price: number
                /** @default null */
                priceWithDisc: null | number
                /** @default 0 */
                count: number
                /** @default [] */
                images: string[]
                /** @default null */
                categoryId: null | number
                /** @default null */
                brandId: null | string
                modifiedName?: string
                articleNumber?: string
              }[]
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/good/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                status: 'draft' | 'published'
                title: string
                /** @default  */
                description: string
                price: number
                /** @default null */
                priceWithDisc: null | number
                /** @default 0 */
                count: number
                /** @default [] */
                images: string[]
                /** @default null */
                categoryId: null | number
                /** @default null */
                brandId: null | string
                modifiedName?: string
                articleNumber?: string
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            status: 'draft' | 'published'
            title: string
            /** @default  */
            description: string
            price: number
            /** @default null */
            priceWithDisc?: null | number
            /** @default 0 */
            count: number
            /** @default [] */
            images: string[]
            /** @default null */
            categoryId?: null | number
            /** @default null */
            brandId?: null | string
            modifiedName?: string
            articleNumber?: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Good */
              data: {
                id: string
                status: 'draft' | 'published'
                title: string
                /** @default  */
                description: string
                price: number
                /** @default null */
                priceWithDisc: null | number
                /** @default 0 */
                count: number
                /** @default [] */
                images: string[]
                /** @default null */
                categoryId: null | number
                /** @default null */
                brandId: null | string
                modifiedName?: string
                articleNumber?: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/good-favorites/{goodId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          goodId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: boolean
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          goodId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: boolean
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          goodId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: boolean
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/good-favorites/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: string[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/basket/{goodId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          goodId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Basket */
              data: {
                goodId: string
                count: number
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          goodId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            count: number
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Basket */
              data: {
                goodId: string
                count: number
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          goodId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Basket */
              data: {
                goodId: string
                count: number
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/basket/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                goodId: string
                count: number
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/brand/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Brand */
              data: {
                id: string
                name: string
                image: string
                description: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Brand */
              data: {
                id: string
                name: string
                image: string
                description: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            name?: string
            image?: string
            description?: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Brand */
              data: {
                id: string
                name: string
                image: string
                description: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
  '/api/brand/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                name: string
                image: string
                description: string
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            name: string
            image: string
            description: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Brand */
              data: {
                id: string
                name: string
                image: string
                description: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/images/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'multipart/form-data': {
            /** Format: binary */
            image: string | unknown
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Image */
              data: {
                name: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/images/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          name: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Image */
              data: {
                name: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/delivery-methods/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            title?: string
            description?: string
            image?: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
  '/api/delivery-methods/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                title: string
                description: string
                image: string
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            title: string
            description: string
            image: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/payment-methods/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            title?: string
            description?: string
            image?: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
  '/api/payment-methods/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                title: string
                description: string
                image: string
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            title: string
            description: string
            image: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** DeliveryMethod */
              data: {
                id: string
                title: string
                description: string
                image: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/transaction/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Transaction */
              data: {
                id: string
                createdAt: string
                updatedAt: string
                status: 'pending' | 'success' | 'error'
                price: number
                checkoutId: string
                providerData: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            status?: 'pending' | 'success' | 'error'
            price?: number
            checkoutId?: string
            providerData?: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Transaction */
              data: {
                id: string
                createdAt: string
                updatedAt: string
                status: 'pending' | 'success' | 'error'
                price: number
                checkoutId: string
                providerData: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
  '/api/transaction/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                createdAt: string
                updatedAt: string
                status: 'pending' | 'success' | 'error'
                price: number
                checkoutId: string
                providerData: string
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/checkout/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Checkout */
              data: {
                id: string
                userId: number
                paymentMethodId: string
                paymentMethodName: string
                deliveryMethodId: string
                deliveryMethodName: string
                recipientName: string
                recipientAddress: string
                recipientPhone: string
                goodsIdList: string[]
                goodsPrice: number[]
                goodsCount: number[]
                goodsName: string[]
                paymentTotal: number
                status: 'created' | 'payed' | 'delivery' | 'delivered' | 'success' | 'canceled'
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/checkout/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                userId: number
                paymentMethodId: string
                paymentMethodName: string
                deliveryMethodId: string
                deliveryMethodName: string
                recipientName: string
                recipientAddress: string
                recipientPhone: string
                goodsIdList: string[]
                goodsPrice: number[]
                goodsCount: number[]
                goodsName: string[]
                paymentTotal: number
                status: 'created' | 'payed' | 'delivery' | 'delivered' | 'success' | 'canceled'
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            deliveryMethodId: string
            recipientName: string
            recipientAddress: string
            recipientPhone: string
            goodsIdList: string[]
            goodsCount: number[]
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Checkout */
              data: {
                id: string
                userId: number
                paymentMethodId: string
                paymentMethodName: string
                deliveryMethodId: string
                deliveryMethodName: string
                recipientName: string
                recipientAddress: string
                recipientPhone: string
                goodsIdList: string[]
                goodsPrice: number[]
                goodsCount: number[]
                goodsName: string[]
                paymentTotal: number
                status: 'created' | 'payed' | 'delivery' | 'delivered' | 'success' | 'canceled'
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/recipient/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Recipient */
              data: {
                name: string
                address: string
                phone: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/news/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** News */
              data: {
                id: string
                title: string
                htmlDocumentName: string
                htmlContent: string
                images: string[]
                status: 'draft' | 'published'
                isPrimary: boolean
                publishedAt: string | null
                createdAt: string
                updatedAt: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/news/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                title: string
                htmlDocumentName: string
                images: string[]
                status: 'draft' | 'published'
                isPrimary: boolean
                publishedAt: string | null
                createdAt: string
                updatedAt: string
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/private/news/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** News */
              data: {
                id: string
                title: string
                htmlDocumentName: string
                htmlContent: string
                images: string[]
                status: 'draft' | 'published'
                isPrimary: boolean
                publishedAt: string | null
                createdAt: string
                updatedAt: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** News */
              data: {
                id: string
                title: string
                htmlDocumentName: string
                images: string[]
                status: 'draft' | 'published'
                isPrimary: boolean
                publishedAt: string | null
                createdAt: string
                updatedAt: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            title?: string
            htmlDocumentName?: string
            htmlContent?: string
            images?: string[]
            status?: 'draft' | 'published'
            isPrimary?: boolean
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** News */
              data: {
                id: string
                title: string
                htmlDocumentName: string
                htmlContent: string
                images: string[]
                status: 'draft' | 'published'
                isPrimary: boolean
                publishedAt: string | null
                createdAt: string
                updatedAt: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
  '/api/private/news/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                id: string
                title: string
                htmlDocumentName: string
                images: string[]
                status: 'draft' | 'published'
                isPrimary: boolean
                publishedAt: string | null
                createdAt: string
                updatedAt: string
              }[]
              total: number
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            title: string
            htmlDocumentName: string
            htmlContent: string
            images: string[]
            status: 'draft' | 'published'
            isPrimary: boolean
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** News */
              data: {
                id: string
                title: string
                htmlDocumentName: string
                htmlContent: string
                images: string[]
                status: 'draft' | 'published'
                isPrimary: boolean
                publishedAt: string | null
                createdAt: string
                updatedAt: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/settings/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Settings */
              data: {
                title: string
                logo: string
              }
            }
          }
        }
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            title?: string
            logo?: string
          }
        }
      }
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              /** Settings */
              data: {
                title: string
                logo: string
              }
            }
          }
        }
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              status: 'ok' | 'error'
              data: {
                message: string
              }
            }
          }
        }
      }
    }
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
